LibroDiarioMayorWebApp/Models/Movimiento.cs
using System;
using System.Collections.Generic;

namespace LibroDiarioMayorWebApp.Models;

public partial class Movimiento
{
    public int IdMovimiento { get; set; }

    public int IdPartida { get; set; }

    public int IdCuenta { get; set; }

    public string NombreCuenta { get; set; } = null!;

    public decimal SaldoMovimiento { get; set; }

    public string TipoMovimiento { get; set; } = null!;
}

LibroDiarioMayorWebApp/Controllers/MovimientosController.cs
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibroDiarioMayorWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using LibroDiarioMayorWebApp.Data;
using System.Data;
using System.Linq;
using MoreLinq;
using System.Security.Claims;
using NuGet.Protocol;
using Microsoft.CodeAnalysis;
using System.ComponentModel.DataAnnotations;
using System.Net;

namespace LibroDiarioMayorWebApp.Controllers
{
    public class MovimientosController : Controller
    {
        private readonly DiarioMayorContext _context;
        public BLLMiscFunctions functions = new BLLMiscFunctions();

        public MovimientosController(DiarioMayorContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "Administrador, Usuario")]
        [HttpPost]
        public IActionResult NuevoMovimiento(int NumeroPartida, DateOnly Fecha, string Descripcion, string Action, int OGId, int[] tIdCuenta, string[] tNombreCuenta, decimal[] tDebe, decimal[] tHaber, int[] tCatalogoNumero, string[] tCatalogoNombre)
        {
            DataTable dataTable = functions.LlenarTablaMovimientos(NumeroPartida, tIdCuenta, tNombreCuenta, tDebe, tHaber);
            DataTable dPartida = functions.LlenarTablaPartida(NumeroPartida, Fecha, Descripcion, dataTable);

            ViewData["Cuentas"] = functions.LlenarTablaCatalogo(tCatalogoNumero, tCatalogoNombre);
            ViewData["Table"] = dataTable;
            ViewData["pDatos"] = dPartida;
            ViewData["Action"] = Action;
            ViewData["OGId"] = OGId;

            return View("Movimientos/Create");
        }
        [Authorize(Roles = "Administrador, Usuario")]
        [HttpPost]
        public IActionResult EditarMovimiento(int NumeroPartida, DateOnly Fecha, string Descripcion, int idMovimiento, string Action, int OGId, int[] tIdCuenta, string[] tNombreCuenta, decimal[] tDebe, decimal[] tHaber, int[] tCatalogoNumero, string[] tCatalogoNombre)
        {
            DataTable dataTable = functions.LlenarTablaMovimientos(NumeroPartida, tIdCuenta, tNombreCuenta, tDebe, tHaber);
            DataTable dPartida = functions.LlenarTablaPartida(NumeroPartida, Fecha, Descripcion, dataTable);

            ViewData["Cuentas"] = functions.LlenarTablaCatalogo(tCatalogoNumero, tCatalogoNombre);
            ViewData["Table"] = dataTable;
            ViewData["pDatos"] = dPartida;
            ViewData["Action"] = Action;
            ViewData["OGId"] = OGId;
            ViewData["IdMovimiento"] = idMovimiento;

            return View("Movimientos/Edit");
        }
        [Authorize(Roles = "Administrador, Usuario")]
        [HttpPost]
        public IActionResult EliminarMovimiento(int NumeroPartida, DateOnly Fecha, string Descripcion, int idMovimiento, string Action, int OGId, int[] tIdCuenta, string[] tNombreCuenta, decimal[] tDebe, decimal[] tHaber, int[] tCatalogoNumero, string[] tCatalogoNombre)
        {
            DataTable dataTable = functions.LlenarTablaMovimientos(NumeroPartida, tIdCuenta, tNombreCuenta, tDebe, tHaber);
            DataTable dPartida = functions.LlenarTablaPartida(NumeroPartida, Fecha, Descripcion, dataTable);

            ViewData["Cuentas"] = functions.LlenarTablaCatalogo(tCatalogoNumero, tCatalogoNombre);
            ViewData["Table"] = dataTable;
            ViewData["pDatos"] = dPartida;
            ViewData["Action"] = Action;
            ViewData["OGId"] = OGId;
            ViewData["IdMovimiento"] = idMovimiento;

            return View("Movimientos/Delete");
        }
        [Authorize(Roles = "Administrador, Usuario")]
        [HttpPost]
        public IActionResult VolverIndexMovimientos(int NumeroPartida, DateOnly Fecha, string Descripcion, string Action, int OGId, int[] tIdCuenta, string[] tNombreCuenta, decimal[] tDebe, decimal[] tHaber, int[] tCatalogoNumero, string[] tCatalogoNombre)
        {
            DataTable dataTable = functions.LlenarTablaMovimientos(NumeroPartida, tIdCuenta, tNombreCuenta, tDebe, tHaber);
            DataTable dPartida = functions.LlenarTablaPartida(NumeroPartida, Fecha, Descripcion, dataTable);

            ViewData["Cuentas"] = functions.LlenarTablaCatalogo(tCatalogoNumero, tCatalogoNombre);
            ViewData["Table"] = dataTable;
            ViewData["pDatos"] = dPartida;
            ViewData["Action"] = Action;
            ViewData["OGId"] = OGId;

            return View("Movimientos/Index");
        }
        [Authorize(Roles = "Administrador, Usuario")]
        [HttpPost]
        public async Task<IActionResult> GuardarTempMovimiento(int IdCuenta, decimal SaldoMovimiento, string TipoMovimiento, int NumeroPartida, DateOnly Fecha, string Descripcion, string Action, int OGId, string[] tIdPartida, int[] tIdCuenta, string[] tNombreCuenta, decimal[] tDebe, decimal[] tHaber, int[] tCatalogoNumero, string[] tCatalogoNombre)
        {
            string CuentaMovida = functions.ObtenerCuentaMovida(tCatalogoNumero, tCatalogoNombre, IdCuenta);

            DataTable dataTable = functions.LlenarTablaMovimientos(NumeroPartida, tIdCuenta, tNombreCuenta, tDebe, tHaber);

            DataRow NewRow = dataTable.NewRow();
            NewRow["IdPartida"] = NumeroPartida;
            NewRow["IdCuenta"] = IdCuenta;
            NewRow["NombreCuenta"] = CuentaMovida;
            if(TipoMovimiento == "Debe")
            {
                NewRow["Debe"] = SaldoMovimiento;
                NewRow["Haber"] = 0;
            }
            else
            {
                NewRow["Debe"] = 0;
                NewRow["Haber"] = SaldoMovimiento;
            }
            dataTable.Rows.Add(NewRow);

            DataTable dPartida = functions. LlenarTablaPartida(NumeroPartida, Fecha, Descripcion, dataTable);

            DataRow rPartida = dPartida.Rows[0];
            rPartida["NumeroPartida"] = NumeroPartida;
            rPartida["Fecha"] = Fecha;
            rPartida["Descripcion"] = Descripcion;
            rPartida["Debe"] = functions.DebeActual(dataTable);
            rPartida["Haber"] = functions.HaberActual(dataTable);
            dPartida.AcceptChanges();

            ViewData["Cuentas"] = functions.LlenarTablaCatalogo(tCatalogoNumero, tCatalogoNombre);
            ViewData["Table"] = dataTable;
            ViewData["pDatos"] = dPartida;
            ViewData["Action"] = Action;
            ViewData["OGId"] = OGId;

            return View("Movimientos/Index");
        }
        [Authorize(Roles = "Administrador, Usuario")]
        [HttpPost]
        public async Task<IActionResult> GuardarEditTempMovimiento(int IdCuenta, decimal SaldoMovimiento, string TipoMovimiento, int NumeroPartida, DateOnly Fecha, string Descripcion, int idMovimiento, string Action, int OGId, string[] tIdPartida, int[] tIdCuenta, string[] tNombreCuenta, decimal[] tDebe, decimal[] tHaber, int[] tCatalogoNumero, string[] tCatalogoNombre)
        {
            string CuentaMovida = functions.ObtenerCuentaMovida(tCatalogoNumero, tCatalogoNombre, IdCuenta);

            DataTable dataTable = functions.LlenarTablaMovimientos(NumeroPartida, tIdCuenta, tNombreCuenta, tDebe, tHaber);

            DataRow EditRow = dataTable.Rows[idMovimiento];
            EditRow["IdPartida"] = NumeroPartida;
            EditRow["IdCuenta"] = IdCuenta;
            EditRow["NombreCuenta"] = CuentaMovida;
            if (TipoMovimiento == "Debe")
            {
                EditRow["Debe"] = SaldoMovimiento;
                EditRow["Haber"] = 0;
            }
            else
            {
                EditRow["Debe"] = 0;
                EditRow["Haber"] = SaldoMovimiento;
            }
            dataTable.AcceptChanges();

            DataTable dPartida = functions.LlenarTablaPartida(NumeroPartida, Fecha, Descripcion, dataTable);

            DataRow rPartida = dPartida.Rows[0];
            rPartida["NumeroPartida"] = NumeroPartida;
            rPartida["Fecha"] = Fecha;
            rPartida["Descripcion"] = Descripcion;
            rPartida["Debe"] = functions.DebeActual(dataTable);
            rPartida["Haber"] = functions.HaberActual(dataTable);
            dPartida.AcceptChanges();

            ViewData["Cuentas"] = functions.LlenarTablaCatalogo(tCatalogoNumero, tCatalogoNombre);
            ViewData["Table"] = dataTable;
            ViewData["pDatos"] = dPartida;
            ViewData["Action"] = Action;
            ViewData["OGId"] = OGId;

            return View("Movimientos/Index");
        }
        [Authorize(Roles = "Administrador, Usuario")]
        [HttpPost]
        public IActionResult GuardarDeleteTempMovimiento(int NumeroPartida, DateOnly Fecha, string Descripcion, int idMovimiento, string Action, int OGId, int[] tIdCuenta, string[] tNombreCuenta, decimal[] tDebe, decimal[] tHaber, int[] tCatalogoNumero, string[] tCatalogoNombre)
        {
            DataTable dataTable = functions.LlenarTablaMovimientos(NumeroPartida, tIdCuenta, tNombreCuenta, tDebe, tHaber);
            dataTable = functions.ActualizarTablaMovimientosIndex(dataTable, idMovimiento, NumeroPartida, tIdCuenta, tNombreCuenta, tDebe, tHaber);

            DataTable dPartida = functions.LlenarTablaPartida(NumeroPartida, Fecha, Descripcion, dataTable);

            DataRow rPartida = dPartida.Rows[0];
            rPartida["NumeroPartida"] = NumeroPartida;
            rPartida["Fecha"] = Fecha;
            rPartida["Descripcion"] = Descripcion;
            rPartida["Debe"] = functions.DebeActual(dataTable);
            rPartida["Haber"] = functions.HaberActual(dataTable);
            dPartida.AcceptChanges();

            ViewData["Cuentas"] = functions.LlenarTablaCatalogo(tCatalogoNumero, tCatalogoNombre);
            ViewData["Table"] = dataTable;
            ViewData["pDatos"] = dPartida;
            ViewData["Action"] = Action;
            ViewData["OGId"] = OGId;

LibroDiarioMayorWebApp/Views/Shared/Movimientos/Create.cshtml
@model LibroDiarioMayorWebApp.Models.Movimiento
@using System.Data;
@using MoreLinq

@{
    ViewData["Title"] = "Crear Movimiento";

    if (ViewData["Action"] != null)
    {
        if (ViewData["Action"].ToString() == "Edit" && User.IsInRole("Usuario") == true)
        {
            <h1>No tienes permiso para acceder a esta funcionalidad</h1>

            <a asp-controller="Home" asp-action="Index">Volver a Inicio</a>
        }
        else
        {
            DataTable catalogo = ViewData["Cuentas"] as DataTable;
            DataTable table = ViewData["Table"] as DataTable;
            DataTable pDatos = ViewData["pDatos"] as DataTable;
            string Action = ViewData["Action"] as string;
            int OGId = Convert.ToInt32(ViewData["OGId"]);



            <h1>Crear Nuevo Movimiento</h1>

            <hr />
            <div class="row">
                <div class="col-md-4">
                    <form asp-action="GuardarTempMovimiento" class="d-grid mb-2">
                        <div class="form-group">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <label asp-for="IdCuenta" class="control-label">Numero de Cuenta</label>
                            <select asp-for="IdCuenta" class="form-select d-grid mb-2">
                                <option value="" disabled selected hidden>Seleccione...</option>
                                @for (int i = 0; i < catalogo.Rows.Count; i++)
                                {
                                    <option value="@catalogo.Rows[i]["NumeroCuenta"]">@catalogo.Rows[i]["NumeroCuenta"] - @catalogo.Rows[i]["NombreCuenta"]</option>
                                }
                            </select>
                            <span asp-validation-for="IdCuenta" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="SaldoMovimiento" class="control-label">Saldo del Movimiento:</label>
                            <input asp-for="SaldoMovimiento" class="form-control d-grid mb-2" />
                            <span asp-validation-for="SaldoMovimiento" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="TipoMovimiento" class="control-label">Tipo de Saldo:</label>
                            <select asp-for="TipoMovimiento" class="form-select d-grid mb-2">
                                <option value="" disabled selected hidden>Seleccione...</option>
                                <option value="Debe">DEBE</option>
                                <option value="Haber">HABER</option>
                            </select>
                            <span asp-validation-for="TipoMovimiento" class="text-danger"></span>
                        </div>
                        <input name="NumeroPartida" type="hidden" value="@pDatos.Rows[0]["NumeroPartida"]" />
                        <input name="Fecha" type="hidden" value="@pDatos.Rows[0]["Fecha"]" />
                        <input name="Descripcion" type="hidden" value="@pDatos.Rows[0]["Descripcion"]" />
                        <input type="hidden" name="Action" value="@Action" />
                        <input type="hidden" name="OGId" value="@OGId" />

                        @for (int i = 0; i < table.Rows.Count; i++)
                        {
                            <input name="tIdCuenta[][]" type="hidden" value="@table.Rows[i]["IdCuenta"]" />
                            <input name="tNombreCuenta[][]" type="hidden" value="@table.Rows[i]["NombreCuenta"]" />
                            <input name="tDebe[][]" type="hidden" value="@table.Rows[i]["Debe"]" />
                            <input name="tHaber[][]" type="hidden" value="@table.Rows[i]["Haber"]" />
                            <input type="hidden" name="Action" value="Create" />
                        }
                        @for (int i = 0; i < catalogo.Rows.Count; i++)
                        {
                            <input name="tCatalogoNumero[][]" type="hidden" value="@catalogo.Rows[i]["NumeroCuenta"]" />
                            <input name="tCatalogoNombre[][]" type="hidden" value="@catalogo.Rows[i]["NombreCuenta"]" />
                        }

                        <div class="form-group">
                            <input type="submit" value="Agregar Movimiento" class="btn btn-primary d-grid mb-2" />
                        </div>
                    </form>
                </div>
            </div>

            <div>
                <form asp-action="VolverIndexMovimientos" class="d-grid mb-2">
                    <input name="NumeroPartida" type="hidden" value="@pDatos.Rows[0]["NumeroPartida"]" />
                    <input name="Fecha" type="hidden" value="@pDatos.Rows[0]["Fecha"]" />
                    <input name="Descripcion" type="hidden" value="@pDatos.Rows[0]["Descripcion"]" />
                    <input type="hidden" name="Action" value="@Action" />
                    <input type="hidden" name="OGId" value="@OGId" />

                    @for (int i = 0; i < table.Rows.Count; i++)
                    {
                        <input name="tIdCuenta[][]" type="hidden" value="@table.Rows[i]["IdCuenta"]" />
                        <input name="tNombreCuenta[][]" type="hidden" value="@table.Rows[i]["NombreCuenta"]" />
                        <input name="tDebe[][]" type="hidden" value="@table.Rows[i]["Debe"]" />
                        <input name="tHaber[][]" type="hidden" value="@table.Rows[i]["Haber"]" />
                    }
                    @for (int i = 0; i < catalogo.Rows.Count; i++)
                    {
                        <input name="tCatalogoNumero[][]" type="hidden" value="@catalogo.Rows[i]["NumeroCuenta"]" />
                        <input name="tCatalogoNombre[][]" type="hidden" value="@catalogo.Rows[i]["NombreCuenta"]" />
                    }
                    <div class="form-group">
                        <input type="submit" value="Volver" class="btn btn-primary d-grid mb-2" />
                    </div>
                </form>
            </div>
        }
    }
    else
    {
        <h1>Ha ocurrido un error</h1>

        <a asp-controller="Home" asp-action="Index">Volver a Inicio</a>

    }
}


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LibroDiarioMayorWebApp/Views/Shared/Movimientos/Index.cshtml
@using System.Data;
@using System.Security.Claims;

@{
    ViewData["Title"] = "Movimientos de Partida";
    
    if (ViewData["Action"] != null)
    {
        if (ViewData["Action"].ToString() == "Edit" && User.IsInRole("Usuario") == true)
        {
            <h1>No tienes permiso para acceder a esta funcionalidad</h1>

            <a asp-controller="Home" asp-action="Index">Volver a Inicio</a>
        }
        else
        {
            DataTable table = ViewData["Table"] as DataTable;
            DataTable pDatos = ViewData["pDatos"] as DataTable;
            DataTable Catalogo = ViewData["Cuentas"] as DataTable;
            string Action = ViewData["Action"] as string;
            int OGId = Convert.ToInt32(ViewData["OGId"]);


            <h1 class="d-grid mb-2">Detalles de Partida:</h1>
            <form asp-action="AccionEditarPartida" asp-controller="Partidas">
                <input name="NumeroPartida" type="hidden" value="@pDatos.Rows[0]["NumeroPartida"]" />
                <input name="Fecha" type="hidden" value="@pDatos.Rows[0]["Fecha"]" />
                <input name="Descripcion" type="hidden" value="@pDatos.Rows[0]["Descripcion"]" />
                <input type="hidden" name="Action" value="@Action" />
                <input type="hidden" name="OGId" value="@OGId" />

                @for (int i = 0; i < table.Rows.Count; i++)
                {
                    <input name="tIdCuenta[][]" type="hidden" value="@table.Rows[i]["IdCuenta"]" />
                    <input name="tNombreCuenta[][]" type="hidden" value="@table.Rows[i]["NombreCuenta"]" />
                    <input name="tDebe[][]" type="hidden" value="@table.Rows[i]["debe"]" />
                    <input name="tHaber[][]" type="hidden" value="@table.Rows[i]["haber"]" />
                }
                @for (int i = 0; i < Catalogo.Rows.Count; i++)
                {
                    <input name="tCatalogoNumero[][]" type="hidden" value="@Catalogo.Rows[i]["NumeroCuenta"]" />
                    <input name="tCatalogoNombre[][]" type="hidden" value="@Catalogo.Rows[i]["NombreCuenta"]" />
                }

                <input type="submit" value="Editar Partida" class="btn btn-primary d-grid mb-2" />
            </form>
            @if (ViewData["Mensaje01"] != null)
            {
                <div class="alert alert-danger" role="alert">
                    @ViewData["Mensaje01"]
                </div>
            }
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>
                            N° de Partida:
                        </th>
                        <th>
                            Fecha:
                        </th>
                        <th>
                            Descripción:
                        </th>
                        <th>
                            DEBE
                        </th>
                        <th>
                            HABER
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            @pDatos.Rows[0]["NumeroPartida"]
                        </td>
                        <td>
                            @pDatos.Rows[0]["Fecha"]
                        </td>
                        <td>
                            @pDatos.Rows[0]["Descripcion"]
                        </td>
                        <td>
                            @pDatos.Rows[0]["Debe"]
                        </td>
                        <td>
                            @pDatos.Rows[0]["Haber"]
                        </td>
                    </tr>
                </tbody>
            </table>

            <h1 class="d-grid mb-2">Movimientos de Partida:</h1>
            <form asp-action="NuevoMovimiento" asp-controller="Movimientos">
                <input name="NumeroPartida" type="hidden" value="@pDatos.Rows[0]["NumeroPartida"]" />
                <input name="Fecha" type="hidden" value="@pDatos.Rows[0]["Fecha"]" />
                <input name="Descripcion" type="hidden" value="@pDatos.Rows[0]["Descripcion"]" />
                <input type="hidden" name="Action" value="@Action" />
                <input type="hidden" name="OGId" value="@OGId" />

                @for (int i = 0; i < table.Rows.Count; i++)
                {
                    <input name="tIdCuenta[][]" type="hidden" value="@table.Rows[i]["IdCuenta"]" />
                    <input name="tNombreCuenta[][]" type="hidden" value="@table.Rows[i]["NombreCuenta"]" />
                    <input name="tDebe[][]" type="hidden" value="@table.Rows[i]["Debe"]" />
                    <input name="tHaber[][]" type="hidden" value="@table.Rows[i]["Haber"]" />
                }
                @for (int i = 0; i < Catalogo.Rows.Count; i++)
                {
                    <input name="tCatalogoNumero[][]" type="hidden" value="@Catalogo.Rows[i]["NumeroCuenta"]" />
                    <input name="tCatalogoNombre[][]" type="hidden" value="@Catalogo.Rows[i]["NombreCuenta"]" />
                }

                <input type="submit" value="Agregar Movimientos" class="btn btn-primary" />
            </form>
            <br>
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>
                            N° de Cuenta:
                        </th>
                        <th width="55%">
                            Nombre de Cuenta:
                        </th>
                        <th>
                            DEBE
                        </th>
                        <th>
                            HABER
                        </th>
                        <th>
                            Acciones:
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @if (table.Rows != null)
                    {
                        ;
                        @for (int i = 0; i < table.Rows.Count; i++)
                        {
                            <tr>
                                <td>
                                    @table.Rows[i]["idCuenta"]
                                </td>
                                <td width="55%">
                                    @table.Rows[i]["NombreCuenta"]
                                </td>
                                <td>
                                    @table.Rows[i]["Debe"]
                                </td>
                                <td>
                                    @table.Rows[i]["Haber"]
                                </td>
                                <td class="small">
                                    <form asp-action="EditarMovimiento" asp-controller="Movimientos" class="c-inline-form">
                                        <input name="NumeroPartida" type="hidden" value="@pDatos.Rows[0]["NumeroPartida"]" />
                                        <input name="Fecha" type="hidden" value="@pDatos.Rows[0]["Fecha"]" />
                                        <input name="Descripcion" type="hidden" value="@pDatos.Rows[0]["Descripcion"]" />
                                        <input type="hidden" name="Action" value="@Action" />
                                        <input type="hidden" name="OGId" value="@OGId" />
                                        <input name="idMovimiento" type="hidden" value="@table.Rows[i]["IdMovimiento"]" />

                                        @for (int j = 0; j < table.Rows.Count; j++)
                                        {
                                            <input name="tIdCuenta[][]" type="hidden" value="@table.Rows[j]["IdCuenta"]" />
                                            <input name="tNombreCuenta[][]" type="hidden" value="@table.Rows[j]["NombreCuenta"]" />
                                            <input name="tDebe[][]" type="hidden" value="@table.Rows[j]["Debe"]" />
                                            <input name="tHaber[][]" type="hidden" value="@table.Rows[j]["Haber"]" />
                                        }
                                        @for (int j = 0; j < Catalogo.Rows.Count; j++)
                                        {
                                            <input name="tCatalogoNumero[][]" type="hidden" value="@Catalogo.Rows[j]["NumeroCuenta"]" />
                                            <input name="tCatalogoNombre[][]" type="hidden" value="@Catalogo.Rows[j]["NombreCuenta"]" />
                                        }

                                        <input type="submit" value="Editar" class="btn btn-primary d-grid gap-2 c-inline-form" />
                                    </form>

                                    <form asp-action="EliminarMovimiento" asp-controller="Movimientos" class="c-inline-form">
                                        <input name="NumeroPartida" type="hidden" value="@pDatos.Rows[0]["NumeroPartida"]" />
                                        <input name="Fecha" type="hidden" value="@pDatos.Rows[0]["Fecha"]" />
                                        <input name="Descripcion" type="hidden" value="@pDatos.Rows[0]["Descripcion"]" />
                                        <input type="hidden" name="Action" value="@Action" />
                                        <input type="hidden" name="OGId" value="@OGId" />
                                        <input name="idMovimiento" type="hidden" value="@table.Rows[i]["IdMovimiento"]" />

                                        @for (int j = 0; j < table.Rows.Count; j++)
                                        {
                                            <input name="tIdCuenta[][]" type="hidden" value="@table.Rows[j]["IdCuenta"]" />
                                            <input name="tNombreCuenta[][]" type="hidden" value="@table.Rows[j]["NombreCuenta"]" />
                                            <input name="tDebe[][]" type="hidden" value="@table.Rows[j]["Debe"]" />
                                            <input name="tHaber[][]" type="hidden" value="@table.Rows[j]["Haber"]" />
                                        }
                                        @for (int j = 0; j < Catalogo.Rows.Count; j++)
                                        {
                                            <input name="tCatalogoNumero[][]" type="hidden" value="@Catalogo.Rows[j]["NumeroCuenta"]" />
                                            <input name="tCatalogoNombre[][]" type="hidden" value="@Catalogo.Rows[j]["NombreCuenta"]" />
                                        }

                                        <input type="submit" value="Eliminar" class="btn btn-primary d-grid gap-2 c-inline-form" />
                                    </form>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
            <form asp-action="AccionGuardarPartida" asp-controller="Partidas">
                <input name="NumeroPartida" type="hidden" value="@pDatos.Rows[0]["NumeroPartida"]" />
                <input name="Fecha" type="hidden" value="@pDatos.Rows[0]["Fecha"]" />
                <input name="Descripcion" type="hidden" value="@pDatos.Rows[0]["Descripcion"]" />
                <input name="Debe" type="hidden" value="@pDatos.Rows[0]["Debe"]" />
                <input name="Haber" type="hidden" value="@pDatos.Rows[0]["Haber"]" />
                <input type="hidden" name="Action" value="@Action" />
                <input type="hidden" name="OGId" value="@OGId" />

                @for (int i = 0; i < table.Rows.Count; i++)
                {
                    <input name="tIdCuenta[][]" type="hidden" value="@table.Rows[i]["IdCuenta"]" />
                    <input name="tNombreCuenta[][]" type="hidden" value="@table.Rows[i]["NombreCuenta"]" />
                    <input name="tDebe[][]" type="hidden" value="@table.Rows[i]["Debe"]" />
                    <input name="tHaber[][]" type="hidden" value="@table.Rows[i]["Haber"]" />
                }
                @for (int i = 0; i < Catalogo.Rows.Count; i++)
                {
                    <input name="tCatalogoNumero[][]" type="hidden" value="@Catalogo.Rows[i]["NumeroCuenta"]" />
                    <input name="tCatalogoNombre[][]" type="hidden" value="@Catalogo.Rows[i]["NombreCuenta"]" />
                }

                <input type="submit" value="Guardar Partida" class="btn btn-primary d-grid mb-2" />
            </form>
        }
    }
    else
    {
        <h1>Ha ocurrido un error</h1>

        <a asp-controller="Home" asp-action="Index">Volver a Inicio</a>

    }


}