LibroDiarioMayorWebApp/Controllers/CatalogoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibroDiarioMayorWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using System.Collections.Immutable;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using MoreLinq;
using LibroDiarioMayorWebApp.Data;

namespace LibroDiarioMayorWebApp.Controllers
{
    [Authorize(Roles = "Administrador")]
    [Authorize]
    public class CatalogoController : Controller
    {
        private readonly DiarioMayorContext _context;

        public CatalogoController(DiarioMayorContext context)
        {
            _context = context;
        }
        public DataTable GetCatalogo()
        {
            DataTable catalogo = _context.Catalogos.ToDataTable();
            return catalogo;


        }
        // GET: Catalogo
        public async Task<IActionResult> Index()
        {
            return View(await _context.Catalogos.ToListAsync());
        }

        // GET: Catalogo/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var catalogo = await _context.Catalogos
                .FirstOrDefaultAsync(m => m.NumeroCuenta == id);
            if (catalogo == null)
            {
                return NotFound();
            }

            return View(catalogo);
        }

        // GET: Catalogo/Create
        public IActionResult Create()
        {
            ViewData["TablaCatalogo"] = GetCatalogo();
            return View();
        }

        // POST: Catalogo/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NumeroCuenta,NombreCuenta,GrupoCuenta,TipoCuenta,ClasificacionCuenta,IncluidaEn,CR")] Catalogo catalogo)
        {
            if (ModelState.IsValid)
            {
                Catalogo? catalogo_Existe = await _context.Catalogos.Where(c => c.NumeroCuenta == catalogo.NumeroCuenta).FirstOrDefaultAsync();
                if (catalogo_Existe != null)
                {
                    ViewData["Mensaje01"] = "Este Número de Cuenta ya esta en uso";
                    return View(catalogo);
                }
                else
                {
                    _context.Add(catalogo);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(catalogo);
        }

        // GET: Catalogo/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var catalogo = await _context.Catalogos.FindAsync(id);
            if (catalogo == null)
            {
                return NotFound();
            }
            return View(catalogo);
        }

        // POST: Catalogo/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NumeroCuenta,NombreCuenta,GrupoCuenta,TipoCuenta,ClasificacionCuenta,IncluidaEn,CR")] Catalogo catalogo)
        {
            if (id != catalogo.NumeroCuenta)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(catalogo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CatalogoExists(catalogo.NumeroCuenta))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(catalogo);
        }

        // GET: Catalogo/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var catalogo = await _context.Catalogos
                .FirstOrDefaultAsync(m => m.NumeroCuenta == id);
            if (catalogo == null)
            {
                return NotFound();
            }

            return View(catalogo);
        }

        // POST: Catalogo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var catalogo = await _context.Catalogos.FindAsync(id);
            if (catalogo != null)
            {
                _context.Catalogos.Remove(catalogo);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CatalogoExists(int id)
        {
            return _context.Catalogos.Any(e => e.NumeroCuenta == id);
        }
    }
}

LibroDiarioMayorWebApp/Controllers/PartidasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibroDiarioMayorWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using LibroDiarioMayorWebApp.Data;
using System.Data;
using MoreLinq;
using System.Security.Claims;
using System.Xml;
using Microsoft.CodeAnalysis.Elfie.Extensions;
using static System.Runtime.InteropServices.JavaScript.JSType;
using System.Security.Cryptography;

namespace LibroDiarioMayorWebApp.Controllers
{
    public class PartidasController : Controller
    {
        private readonly DiarioMayorContext _context;
        public BLLMiscFunctions functions = new BLLMiscFunctions();

        public PartidasController(DiarioMayorContext context)
        {
            _context = context;
        }

        // GET: Partidas
        [Authorize(Roles = "Administrador, Usuario")]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            
            return View("Partidas/Index", await _context.Partidas.ToListAsync());
        }

        // GET: Partidas/Details/5
        [Authorize(Roles = "Administrador, Usuario")]
        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var partida = await _context.Partidas
                .FirstOrDefaultAsync(m => m.NumeroPartida == id);
            if (partida == null)
            {
                return NotFound();
            }
            DataTable allMov = _context.Movimientos.ToDataTable();
            DataTable dataTable = functions.NuevaTablaMovimientos();
            for (int i = 0; i < allMov.Rows.Count; i++)
            {
                if (Convert.ToInt32(allMov.Rows[i]["IdPartida"]) == id)
                {
                    DataRow row = dataTable.NewRow();
                    row["IdPartida"] = allMov.Rows[i][1];
                    row["IdCuenta"] = allMov.Rows[i][2];
                    row["NombreCuenta"] = allMov.Rows[i][3];
                    if (allMov.Rows[i][5].ToString() == "DEBE")
                    {
                        row["Debe"] = allMov.Rows[i][4];
                    }
                    else
                    {
                        row["Haber"] = allMov.Rows[i][4];
                    }

                    dataTable.Rows.Add(row);
                }
            }
            dataTable.AcceptChanges();

            DataTable pDatos = functions.LlenarTablaPartida(partida.NumeroPartida, partida.Fecha, partida.Descripcion, dataTable);

            ViewData["Table"] = dataTable;
            ViewData["pDatos"] = pDatos;
            ViewData["IngresadoPor"] = partida.IngresadoPor;
            return View("Partidas/Details");
        }

        // GET: Partidas/Create
        [Authorize(Roles = "Administrador, Usuario")]
        [HttpGet]
        public IActionResult Create()
        {
            ViewData["Cuentas"] = _context.Catalogos.ToDataTable();
            return View("Partidas/Create");
        }
        // POST: Partidas/Create
        [HttpPost]
        public IActionResult AccionNuevaPartida(int NumeroPartida, DateOnly Fecha, string Descripcion, int[] tCatalogoNumero, string[] tCatalogoNombre, string Action)
        {
            ViewData["Cuentas"] = functions.LlenarTablaCatalogo(tCatalogoNumero, tCatalogoNombre);
            ViewData["Table"] = functions.NuevaTablaMovimientos();
            ViewData["pDatos"] = functions.LlenarTablaPartida(NumeroPartida, Fecha, Descripcion, functions.NuevaTablaMovimientos());
            ViewData["Action"] = Action;
            return View("Movimientos/Index");
        }
        // POST: ir aPartidas/Edit
        [HttpPost]
        public IActionResult AccionEditarPartida(int NumeroPartida, DateOnly Fecha, string Descripcion, string Action, int OGId, int[] tIdCuenta, string[] tNombreCuenta, decimal[] tDebe, decimal[] tHaber, int[] tCatalogoNumero, string[] tCatalogoNombre)
        {
            ViewData["Cuentas"] = functions.LlenarTablaCatalogo(tCatalogoNumero, tCatalogoNombre);
            ViewData["Table"] = functions.LlenarTablaMovimientos(NumeroPartida, tIdCuenta, tNombreCuenta, tDebe, tHaber);
            ViewData["pDatos"] = functions.LlenarTablaPartida(NumeroPartida, Fecha, Descripcion, functions.LlenarTablaMovimientos(NumeroPartida, tIdCuenta, tNombreCuenta, tDebe, tHaber));
            ViewData["Action"] = Action;
            ViewData["OGId"] = OGId;
            return View("Partidas/Edit");
        }
        // POST: volviendo de Partidas/Edit
        [HttpPost]
        public IActionResult PartidaVolverIndexMovimientos(int NumeroPartida, DateOnly Fecha, string Descripcion, string Action, int OGId, int[] tIdCuenta, string[] tNombreCuenta, decimal[] tDebe, decimal[] tHaber, int[] tCatalogoNumero, string[] tCatalogoNombre)
        {
            ViewData["Cuentas"] = functions.LlenarTablaCatalogo(tCatalogoNumero, tCatalogoNombre);
            ViewData["Table"] = functions.LlenarTablaMovimientos(NumeroPartida, tIdCuenta, tNombreCuenta, tDebe, tHaber);
            ViewData["pDatos"] = functions.LlenarTablaPartida(NumeroPartida, Fecha, Descripcion, functions.LlenarTablaMovimientos(NumeroPartida, tIdCuenta, tNombreCuenta, tDebe, tHaber));
            ViewData["Action"] = Action;
            ViewData["OGId"] = OGId;
            return View("Movimientos/Index");
        }

        // POST: guardando datos de Partidas/Edit
        [HttpPost]
        public IActionResult AccionGuardarEditPartida(int NumeroPartida, DateOnly Fecha, string Descripcion, string Action, int OGId, int[] tIdCuenta, string[] tNombreCuenta, decimal[] tDebe, decimal[] tHaber, int[] tCatalogoNumero, string[] tCatalogoNombre)
        {
            ViewData["Cuentas"] = functions.LlenarTablaCatalogo(tCatalogoNumero, tCatalogoNombre);
            ViewData["Table"] = functions.LlenarTablaMovimientos(NumeroPartida, tIdCuenta, tNombreCuenta, tDebe, tHaber);
            ViewData["pDatos"] = functions.LlenarTablaPartida(NumeroPartida, Fecha, Descripcion, functions.LlenarTablaMovimientos(NumeroPartida, tIdCuenta, tNombreCuenta, tDebe, tHaber));
            ViewData["Action"] = Action;
            ViewData["OGId"] = OGId;
            return View("Movimientos/Index");
        }
        // POST: Guardando Partida de Movimientos/Index
        [Authorize(Roles = "Administrador, Usuario")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AccionGuardarPartida(int NumeroPartida, DateOnly Fecha, string Descripcion, string Action, int OGId, decimal Debe, decimal Haber, string[] tIdPartida, int[] tIdCuenta, string[] tNombreCuenta, decimal[] tDebe, decimal[] tHaber, int[] tCatalogoNumero, string[] tCatalogoNombre)
        {
            DataTable dataTable = functions.LlenarTablaMovimientos(NumeroPartida, tIdCuenta, tNombreCuenta, tDebe, tHaber);
            DataTable pDatos = functions.LlenarTablaPartida(NumeroPartida, Fecha, Descripcion, dataTable);
            if (_context.Partidas.Where(p => p.NumeroPartida == NumeroPartida).FirstOrDefault() != null && Action != "Edit")
            {
                ViewData["Mensaje01"] = "Este numero de partida ya existe, defina uno nuevo";
                ViewData["Cuentas"] = functions.LlenarTablaCatalogo(tCatalogoNumero, tCatalogoNombre);
                ViewData["Table"] = dataTable;
                ViewData["pDatos"] = pDatos;
                ViewData["Action"] = Action;
                ViewData["OGId"] = OGId;

                return View("Movimientos/Index");
            }
            if (Debe != Haber || Debe <= 0 || Haber <= 0)
            {
                if (Debe <= 0 || Haber <= 0)
                {
                    ViewData["Mensaje01"] = "El DEBE y el HABER no pueden ser igual o menor que 0";
                }
                else
                {
                    ViewData["Mensaje01"] = "El DEBE total y el HABER total no coinciden";
                }
                ViewData["Cuentas"] = functions.LlenarTablaCatalogo(tCatalogoNumero, tCatalogoNombre);
                ViewData["Table"] = dataTable;
                ViewData["pDatos"] = pDatos;
                ViewData["Action"] = Action;
                ViewData["OGId"] = OGId;

                return View("Movimientos/Index");
            }
            else
            {
                if (Action == "Create")
                {
                    _context.CreatePartidaMovimientos(NumeroPartida, dataTable, pDatos, User.Claims.Where(u => u.Type == ClaimTypes.Name).Select(v => v.Value).SingleOrDefault());
                    _context.SaveChanges();
                    return View("Partidas/Index", await _context.Partidas.ToListAsync());
                }
                else
                {
                    if (User.IsInRole("Usuario") == true)
                    {
                        ViewData["Mensaje01"] = "No tienes permiso para acceder a esta funcionalidad";
                        return View("Partidas/Index");
                    }
                    _context.EditPartidaMovimientos(NumeroPartida, dataTable, pDatos, User.Claims.Where(u => u.Type == ClaimTypes.Name).Select(v => v.Value).SingleOrDefault(), OGId);
                    _context.SaveChanges();
                    return View("Partidas/Index", await _context.Partidas.ToListAsync());
                }
            }
        }

        // GET: Partidas/Edit/5
        [Authorize(Roles = "Administrador")]
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var partida = await _context.Partidas.FindAsync(id);
            if (partida == null)
            {
                return NotFound();
            }

LibroDiarioMayorWebApp/Views/Shared/_Layout.cshtml
@using System.Security.Claims;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibroDiarioMayorWebApp</title>
    <link rel="icon" type="image/x-icon" href="/img/TabLogo.ico" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibroDiarioMayorWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand layout-nav" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link layout-nav" asp-area="" asp-controller="Partidas" asp-action="Index">Libro Diario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link layout-nav" asp-area="" asp-controller="Mayor" asp-action="LibroMayor">Libro Mayor</a>
                        </li>

                        @if (User.IsInRole("Administrador"))
                        {
                            <li class="nav-item">
                                <a class="nav-link layout-nav" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                            </li>
                        }
                        
                        @if (User.IsInRole("Administrador"))
                        {
                            <li class="nav-item">
                                <a class="nav-link layout-nav" asp-area="" asp-controller="Catalogo" asp-action="Index">Catalogo de Cuentas</a>
                            </li>
                        }
                        
                        @if (User.IsInRole("Administrador"))
                        {
                            <div class="dropdown">
                                <a class="nav-link layout-nav" href="#">Estados Financieros</a>
                                <div class="dropdown-content">
                                    <a class="dropdown-item" asp-controller="Mayor" asp-action="BalanceGeneral">Balance General</a>
                                    <a class="dropdown-item" asp-controller="Mayor" asp-action="EstadoResultado">Estado de Resultado</a>
                                </div>
                            </div>
                        }
                    </ul>
                    <div class="dropdown">
                        <input type="image" src="~/img/Logo.png" class="dropbtn me-auto img-fluid" />
                        <div class="dropdown-content">
                            <a class="dropdown-item" asp-controller="Usuarios" asp-action="Details" asp-route-id="@Convert.ToInt32(User.Claims.Where(c => c.Type == ClaimTypes.NameIdentifier).Select(c => c.Value).SingleOrDefault()) ">Ver Perfil</a>
                            <a class="dropdown-item" asp-controller="Home" asp-action="Logout">Cerrar Sesión</a>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Aplicación de Libros Contables: Diario y Mayor - Desarrollado por Carlos Fernando Hernandez Léon
            <b class="float-end">Versión 1.0.2</b>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<!----<img class="me-auto img-fluid" src="~/img/Logo.png" width="40px" height="40 px"></a>-->

LibroDiarioMayorWebApp/Views/Shared/_LayoutVacio.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibroDiarioMayorWebApp</title>
    <link rel="icon" type="image/x-icon" href="/img/TabLogo.ico" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibroDiarioMayorWebApp.styles.css" asp-append-version="true" />
</head>
<body>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

</body>
</html>